# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(400, 400)
        SecondWindow.setMinimumSize(QtCore.QSize(400, 400))
        SecondWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cartmenu_label = QtWidgets.QLabel(self.centralwidget)
        self.cartmenu_label.setGeometry(QtCore.QRect(130, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.cartmenu_label.setFont(font)
        self.cartmenu_label.setObjectName("cartmenu_label")
        self.cookie_label = QtWidgets.QLabel(self.centralwidget)
        self.cookie_label.setGeometry(QtCore.QRect(40, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cookie_label.setFont(font)
        self.cookie_label.setObjectName("cookie_label")
        self.sandwich_label = QtWidgets.QLabel(self.centralwidget)
        self.sandwich_label.setGeometry(QtCore.QRect(40, 110, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sandwich_label.setFont(font)
        self.sandwich_label.setObjectName("sandwich_label")
        self.water_label = QtWidgets.QLabel(self.centralwidget)
        self.water_label.setGeometry(QtCore.QRect(40, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.water_label.setFont(font)
        self.water_label.setObjectName("water_label")
        self.total_label = QtWidgets.QLabel(self.centralwidget)
        self.total_label.setGeometry(QtCore.QRect(90, 190, 211, 111))
        self.total_label.setText("")
        self.total_label.setObjectName("total_label")
        self.exit2_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit2_button.setGeometry(QtCore.QRect(220, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.exit2_button.setFont(font)
        self.exit2_button.setObjectName("exit2_button")
        self.grandtotal_button = QtWidgets.QPushButton(self.centralwidget)
        self.grandtotal_button.setGeometry(QtCore.QRect(70, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.grandtotal_button.setFont(font)
        self.grandtotal_button.setObjectName("grandtotal_button")
        self.cookie_input = QtWidgets.QLineEdit(self.centralwidget)
        self.cookie_input.setGeometry(QtCore.QRect(240, 70, 113, 20))
        self.cookie_input.setObjectName("cookie_input")
        self.sandwich_input = QtWidgets.QLineEdit(self.centralwidget)
        self.sandwich_input.setGeometry(QtCore.QRect(240, 110, 113, 20))
        self.sandwich_input.setObjectName("sandwich_input")
        self.water_input = QtWidgets.QLineEdit(self.centralwidget)
        self.water_input.setGeometry(QtCore.QRect(240, 150, 113, 20))
        self.water_input.setObjectName("water_input")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Cart Menu - The Internet Cafe"))
        self.cartmenu_label.setText(_translate("SecondWindow", "Cart Menu"))
        self.cookie_label.setText(_translate("SecondWindow", "Cookie - $1.50"))
        self.sandwich_label.setText(_translate("SecondWindow", "Sandwich - $4.00"))
        self.water_label.setText(_translate("SecondWindow", "Water - $1.50"))
        self.exit2_button.setText(_translate("SecondWindow", "EXIT"))
        self.grandtotal_button.setText(_translate("SecondWindow", "TOTAL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
